---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ticket-service-postgres
  annotations:
    a8r.io/description: "Properties for postgres connection"
stringData:

  PGUSER: ticketpg
  PGPASSWORD: ...
  PGHOST: ha-postgres
  PGPORT: "5432"
  PGDATABASE: ticket-service

  # Connection settings
  SQLALCHEMY_DATABASE_URI: postgresql://ticketpg:...@ha-postgres:5432/ticket-service