---
steps:
  - trigger: "kaniko"
    label: ":buildkite: Trigger build pipeline"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: "${BUILDKITE_BRANCH}"
      env:
        REGISTRY: renato.jfrog.io
        REGISTRY_REPOSITORY: local-docker
        IMAGE_NAME: ticket-service
        IMAGE_TAG: latest
        BITBUCKET_CONTEXT_REPO: "${BUILDKITE_GIT_REPO}"