---
steps:
  - label: ":package: Package repository"
    command: ".buildkite/scripts/package.sh"
    agents:
      env: kubernetes
      namespace: services
      privileged: false

  - wait

  - trigger: "kaniko"
    label: ":buildkite: Trigger build pipeline"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: "${BUILDKITE_BRANCH}"
      env:
        REGISTRY: "${REGISTRY}"
        REGISTRY_REPOSITORY: "${REGISTRY_REPOSITORY}"
        IMAGE_NAME: "${IMAGE_NAME}"
        IMAGE_TAG: "${IMAGE_TAG}"

env:
  REGISTRY: renatodamas.jfrog.io
  REGISTRY_REPOSITORY: local-docker
  IMAGE_NAME: ticket-service
  IMAGE_TAG: latest