---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ticket-api
stringData:

  # O365 registered tenant
  O365_TENANT_ID: ...

  # O365 client credentials
  O365_CLIENT_ID: ...
  O365_CLIENT_SECRET: ...

  # Atlassian credentials
  ATLASSIAN_USER: me@example.com
  ATLASSIAN_API_TOKEN: ...
