---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ticket-api-db
  annotations:
    a8r.io/description: Properties for postgres connection
stringData:

  PGUSER: ...
  PGPASSWORD: ...
  PGHOST: postgres
  PGPORT: "5432"
  PGDATABASE: ticket-api

  # Connection settings
  SQLALCHEMY_DATABASE_URI: postgresql://...:...@postgres:5432/ticket-api
