---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services

resources:
  - ../../base/
  - secrets/sealed/

components:
  - ../../components/api/
  - ../../components/bridge/
  - configs/
  - ingress/

images:
  - name: ticket-service
    newName: ...
    newTag: latest