---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services

resources:
  - sealed-secrets
  - ../../base/

components:
  - ../../components/api/
  - ../../components/bridge/