---
openapi: "{OPENAPI}"
info:
  title: Ticket manager service
  description': Service to manage tickets and Jira integration.
  version: 1.0.0

servers:
  - url: "{APPLICATION_CONTEXT}"
    description: dev

tags:
  - name: tickets
    description: All operations involving tickets

components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
    UnsupportedMediaType:
      description: Unsupported Media Type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpError'
